### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by msm1314zjq** [aviogit/dynamic-hand-gesture-classification#2]
hello,Would you mind showing me your paper?I looked for it for a long time but I couldn't find it.

**Comment by aviogit** [comment]
Hey there! Of course, the first paper is this one: https://arxiv.org/abs/2003.01450 then we just published a second paper that required a double-blind review with anonymous repo for the code. This is the paper: https://www.sciencedirect.com/science/article/abs/pii/S0097849320301163?dgcid=raven_sd_aip_email and this is the anonymous repo: https://github.com/dynamic-hand-gestures-classification/dynamic-hand-gestures-classification

This thing is beginning to work decently, we did about 75% accuracy on the unsegmented SFINGE 3D dataset. In the anonymous repo you can find the procedure to setup a virtual env to start using the visualizer. Through the visualizer, you can then generate images to train the ResNet via the jupyter notebook (also included).

Good luck! :)
